#!/bin/bash

if [ "$1" == "car" ]; then
    ./make_grid_car.py
    ./polarmc_car
elif [ "$1" == "cyl" ]; then
    ./make_grid_cyl.py
    ./polarmc_cyl
elif [ "$1" == "sph" ]; then
    ./make_grid_sph.py
    ./polarmc_sph
elif [ "$1" == "car_omp" ]; then
    ./make_grid_car.py
    ./polarmc_car_omp
elif [ "$1" == "cyl_omp" ]; then
    ./make_grid_cyl.py
    ./polarmc_cyl_omp
elif [ "$1" == "sph_omp" ]; then
    ./make_grid_sph.py
    ./polarmc_sph_omp
else
    echo "$1 is not a valid option."
fi
